"""VvC Second Brain — Markdown Sanitizer & Invariant Enforcer (v8.15.11).

Centralized Deep Seam for enforcing Vault markdown hygiene:
- Clean Wikilink Invariant (AGENTS.md §4.4): removes accidental quotes and backticks wrapping wikilinks
- Mermaid Edge Label Invariant (AGENTS.md §4.4, §4.10): heals chimeric edge labels and normalizes comparison operators (>= -> ≥, <= -> ≤)
- Strict HTML Entity Context Isolation (AGENTS.md §4.4): confines #40; and #41; strictly to ```mermaid blocks and reverts to () outside
- Artifact Embed Syntax: normalizes malformed diagram extensions inside ![[...]] embeds
"""

from __future__ import annotations

import logging
import re

_logger = logging.getLogger("vvc.sanitizer")

__all__ = [
    "heal_mermaid_edge_syntax",
    "heal_html_entity_leakage",
    "heal_artifact_embed_syntax",
    "clean_wikilink_quotes",
]


def heal_mermaid_edge_syntax(text: str) -> str:
    """Normalize chimeric edge labels in Mermaid diagrams.

    Converts hallucinated syntax like:
        HUB ===="label"====> SPOKES -> HUB ===>|"label"| SPOKES
        SPOKES -."label".-> HUB     -> SPOKES -.->|"label"| HUB
        HUB <===="label"====> SPOKES -> HUB <===>|"label"| SPOKES
    Also normalizes comparison operators inside labels:
        >= -> ≥, <= -> ≤

    Args:
        text: Input markdown or mermaid text.

    Returns:
        Sanitized text with standard Mermaid edge label syntax.
    """
    def _normalize_label(label: str) -> str:
        label = label.strip()
        label = re.sub(r">=", "≥", label)
        label = re.sub(r"<=", "≤", label)
        return label

    def _repl_bidirectional(m: re.Match) -> str:
        label = _normalize_label(m.group(1))
        _logger.warning(f"[Mermaid Sanitizer] Auto-corrected bidirectional edge label: {m.group(0)!r} -> <===>|\"{label}\"|")
        return f'<===>|"{label}"|'

    def _repl_dotted(m: re.Match) -> str:
        label = _normalize_label(m.group(1))
        _logger.warning(f"[Mermaid Sanitizer] Auto-corrected dotted edge label: {m.group(0)!r} -> -.->|\"{label}\"|")
        return f'-.->|"{label}"|'

    def _repl_thick(m: re.Match) -> str:
        label = _normalize_label(m.group(1))
        _logger.warning(f"[Mermaid Sanitizer] Auto-corrected thick edge label: {m.group(0)!r} -> ===>|\"{label}\"|")
        return f'===>|"{label}"|'

    # 1. Bidirectional thick edge: <====="..."====> or <==="..."==>
    text = re.sub(r"<=+\s*\"([^\"]+)\"\s*=+>", _repl_bidirectional, text)
    # 2. Dotted edge: -."..."-.->, -."...".->, -."..."->
    text = re.sub(r"-\.\s*\"([^\"]+)\"\s*[-.]*->", _repl_dotted, text)
    # 3. Forward thick edge: ===="..."====> or =="...""==>
    text = re.sub(r"(?<!<)=+\s*\"([^\"]+)\"\s*=+>", _repl_thick, text)

    # 4. Proactive normalization for existing pipe labels containing comparison operators
    def _repl_pipe(m: re.Match) -> str:
        content = m.group(1)
        if ">=" in content or "<=" in content:
            content = _normalize_label(content)
        return f"|{content}|"

    text = re.sub(r"\|([^|\n]+)\|", _repl_pipe, text)

    return text


def heal_html_entity_leakage(text: str) -> str:
    """Normalize leaked #40; and #41; entities in Markdown tables and body text.

    Preserves #40; and #41; inside ```mermaid blocks where they prevent shape parse errors.
    Reverts them to '(' and ')' everywhere outside ```mermaid blocks.
    Also applies heal_mermaid_edge_syntax on lines inside Mermaid blocks.

    Args:
        text: Input markdown text.

    Returns:
        Sanitized markdown text.
    """
    lines = text.split("\n")
    out_lines = []
    in_mermaid = False

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("```mermaid"):
            in_mermaid = True
            out_lines.append(line)
        elif in_mermaid and stripped.startswith("```"):
            in_mermaid = False
            out_lines.append(line)
        elif in_mermaid:
            # Inside Mermaid: heal edge syntax, preserve #40; / #41;
            out_lines.append(heal_mermaid_edge_syntax(line))
        else:
            # Outside Mermaid: revert leaked #40; / #41;
            if "#40;" in line or "#41;" in line:
                _logger.warning(f"[Entity Sanitizer] Auto-corrected leaked HTML entity outside Mermaid: {line[:80]}")
                line = line.replace("#40;", "(").replace("#41;", ")")
            out_lines.append(line)

    return "\n".join(out_lines)


def clean_wikilink_quotes(text: str) -> str:
    """Clean up accidental quotes inside wikilinks generated by LLM.

    Converts ![["filename.png"]] -> ![[filename.png]] and [["note.md"]] -> [[note.md]].
    Normalizes artifact embed extensions and heals Mermaid edge / entity leakage.

    Args:
        text: Input markdown text.

    Returns:
        Sanitized markdown text.
    """
    def _repl(m: re.Match) -> str:
        prefix = m.group(1)
        name = m.group(2)
        alias = m.group(3) or ""
        return f"{prefix}{name}{alias}]]"

    text = re.sub(r'(!?\[\[)"(.*?)"(\|.*?)?\]\]', _repl, text)
    text = re.sub(r"(!?\[\[)'(.*?)'(\|.*?)?\]\]", _repl, text)
    # Strip accidental backticks wrapping wikilinks: `[[note]]` -> [[note]] or `[[note|alias]]` -> [[note|alias]]
    text = re.sub(r"`(!?\[\[[^`\n]+?\]\])`", r"\1", text)
    text = heal_artifact_embed_syntax(text)
    text = heal_html_entity_leakage(text)
    return text


def heal_artifact_embed_syntax(text: str) -> str:
    """Normalize malformed snake_cased diagram extensions inside embed wikilinks.

    Examples:
        ![[foo_excalidraw_md]] -> ![[foo.excalidraw.md]]
        ![[foo_excalidraw_md|100%]] -> ![[foo.excalidraw.md|100%]]
        ![[bar_mermaid_md|800]] -> ![[bar.mermaid.md|800]]
        ![[baz_d2_svg]] -> ![[baz.d2.svg]]

    Args:
        text: Input markdown text.

    Returns:
        Sanitized markdown text with valid diagram extensions.
    """
    text = re.sub(r"!\[\[([^\]|]+)_excalidraw_md(\|[^\]]*)?\]\]", r"![[\1.excalidraw.md\2]]", text)
    text = re.sub(r"!\[\[([^\]|]+)_mermaid_md(\|[^\]]*)?\]\]", r"![[\1.mermaid.md\2]]", text)
    text = re.sub(r"!\[\[([^\]|]+)_d2_svg(\|[^\]]*)?\]\]", r"![[\1.d2.svg\2]]", text)
    return text
