"""VvC Second Brain — Command Citations & Wikilink Formatting.

Pure functional citation reindexing and wikilink quote sanitization.
"""

from __future__ import annotations

import re


def clean_wikilink_quotes(text: str) -> str:
    """Clean up accidental quotes inside wikilinks generated by LLM.

    Converts ![["filename.png"]] -> ![[filename.png]] and [["note.md"]] -> [[note.md]].

    Args:
        text: Input markdown text.

    Returns:
        Sanitized markdown text.
    """
    def _repl(m: re.Match) -> str:
        prefix = m.group(1)
        name = m.group(2)
        alias = m.group(3) or ""
        return f"{prefix}{name}{alias}]]"

    text = re.sub(r'(!?\[\[)"(.*?)"(\|.*?)?\]\]', _repl, text)
    text = re.sub(r"(!?\[\[)'(.*?)'(\|.*?)?\]\]", _repl, text)
    return text


def reindex_citations(response: str, rag_refs: dict[int, tuple[str, str]]) -> str:
    """Reindex numeric citations in response ([14] -> [1]) and append reference list.

    Args:
        response: LLM response containing citations like [14] or |[14]|.
        rag_refs: Mapping of reference IDs to (filename, file_title).

    Returns:
        Response with reindexed citations and appended '## Tài liệu tham chiếu' section.
    """
    if not rag_refs:
        return response

    used_ids: list[int] = []
    for match in re.finditer(r"\[(\d+)\]|\|\[?(\d+)\]?\]\]", response):
        val = match.group(1) or match.group(2)
        if val:
            try:
                parsed_id = int(val)
                if parsed_id not in used_ids:
                    used_ids.append(parsed_id)
            except ValueError:
                pass

    if not used_ids:
        return response

    valid_ids = [i for i in used_ids if i in rag_refs]
    if not valid_ids:
        return response

    id_map = {old_id: new_id for new_id, old_id in enumerate(valid_ids, 1)}

    def _replace_id(match: re.Match) -> str:
        if match.group(1):
            old_id = int(match.group(1))
            if old_id in id_map:
                return f"[{id_map[old_id]}]"
        elif match.group(2):
            old_id = int(match.group(2))
            if old_id in id_map:
                original = match.group(0)
                if f"[{old_id}]" in original:
                    return original.replace(f"[{old_id}]", f"[{id_map[old_id]}]")
                else:
                    return original.replace(str(old_id), str(id_map[old_id]))
        return match.group(0)

    response = re.sub(r"\[(\d+)\]|\|\[?(\d+)\]?\]\]", _replace_id, response)

    ref_block = "\n\n---\n\n## Tài liệu tham chiếu\n"
    for old_id in valid_ids:
        fname, ftitle = rag_refs[old_id]
        new_id = id_map[old_id]
        ref_block += f"{new_id}. [[{fname}|{ftitle}]]\n"

    if "]. [[" in ref_block or ". [[" in ref_block:
        response += ref_block

    return response
