"""VvC Second Brain — Command Citations & Wikilink Formatting.

Pure functional citation reindexing and wikilink quote sanitization.
"""

from __future__ import annotations

import logging
import re

_logger = logging.getLogger("vvc.citations")


def heal_mermaid_edge_syntax(text: str) -> str:
    """Normalize chimeric edge labels in Mermaid diagrams.

    Converts hallucinated syntax like:
        HUB ===="label"====> SPOKES -> HUB ===>|"label"| SPOKES
        SPOKES -."label".-> HUB     -> SPOKES -.->|"label"| HUB
        HUB <===="label"====> SPOKES -> HUB <===>|"label"| SPOKES
    Also normalizes comparison operators inside labels:
        >= -> ≥, <= -> ≤

    Args:
        text: Input markdown or mermaid text.

    Returns:
        Sanitized text with standard Mermaid edge label syntax.
    """
    def _normalize_label(label: str) -> str:
        label = label.strip()
        label = re.sub(r">=", "≥", label)
        label = re.sub(r"<=", "≤", label)
        return label

    def _repl_bidirectional(m: re.Match) -> str:
        label = _normalize_label(m.group(1))
        _logger.warning(f"[Mermaid Sanitizer] Auto-corrected bidirectional edge label: {m.group(0)!r} -> <===>|\"{label}\"|")
        return f'<===>|"{label}"|'

    def _repl_dotted(m: re.Match) -> str:
        label = _normalize_label(m.group(1))
        _logger.warning(f"[Mermaid Sanitizer] Auto-corrected dotted edge label: {m.group(0)!r} -> -.->|\"{label}\"|")
        return f'-.->|"{label}"|'

    def _repl_thick(m: re.Match) -> str:
        label = _normalize_label(m.group(1))
        _logger.warning(f"[Mermaid Sanitizer] Auto-corrected thick edge label: {m.group(0)!r} -> ===>|\"{label}\"|")
        return f'===>|"{label}"|'

    # 1. Bidirectional thick edge: <====="..."====> or <==="..."==>
    text = re.sub(r"<=+\s*\"([^\"]+)\"\s*=+>", _repl_bidirectional, text)
    # 2. Dotted edge: -."..."-.->, -."...".->, -."..."->
    text = re.sub(r"-\.\s*\"([^\"]+)\"\s*[-.]*->", _repl_dotted, text)
    # 3. Forward thick edge: ===="..."====> or =="...""==>
    text = re.sub(r"(?<!<)=+\s*\"([^\"]+)\"\s*=+>", _repl_thick, text)

    # 4. Proactive normalization for existing pipe labels containing comparison operators
    def _repl_pipe(m: re.Match) -> str:
        content = m.group(1)
        if ">=" in content or "<=" in content:
            content = _normalize_label(content)
        return f"|{content}|"

    text = re.sub(r"\|([^|\n]+)\|", _repl_pipe, text)

    return text


def heal_html_entity_leakage(text: str) -> str:
    """Normalize leaked #40; and #41; entities in Markdown tables and body text.

    Preserves #40; and #41; inside ```mermaid blocks where they prevent shape parse errors.
    Reverts them to '(' and ')' everywhere outside ```mermaid blocks.
    Also applies heal_mermaid_edge_syntax on lines inside Mermaid blocks.

    Args:
        text: Input markdown text.

    Returns:
        Sanitized markdown text.
    """
    lines = text.split("\n")
    out_lines = []
    in_mermaid = False

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("```mermaid"):
            in_mermaid = True
            out_lines.append(line)
        elif in_mermaid and stripped.startswith("```"):
            in_mermaid = False
            out_lines.append(line)
        elif in_mermaid:
            # Inside Mermaid: heal edge syntax, preserve #40; / #41;
            out_lines.append(heal_mermaid_edge_syntax(line))
        else:
            # Outside Mermaid: revert leaked #40; / #41;
            if "#40;" in line or "#41;" in line:
                _logger.warning(f"[Entity Sanitizer] Auto-corrected leaked HTML entity outside Mermaid: {line[:80]}")
                line = line.replace("#40;", "(").replace("#41;", ")")
            out_lines.append(line)

    return "\n".join(out_lines)


def clean_wikilink_quotes(text: str) -> str:
    """Clean up accidental quotes inside wikilinks generated by LLM.

    Converts ![["filename.png"]] -> ![[filename.png]] and [["note.md"]] -> [[note.md]].
    Normalizes artifact embed extensions and heals Mermaid edge / entity leakage.

    Args:
        text: Input markdown text.

    Returns:
        Sanitized markdown text.
    """
    def _repl(m: re.Match) -> str:
        prefix = m.group(1)
        name = m.group(2)
        alias = m.group(3) or ""
        return f"{prefix}{name}{alias}]]"

    text = re.sub(r'(!?\[\[)"(.*?)"(\|.*?)?\]\]', _repl, text)
    text = re.sub(r"(!?\[\[)'(.*?)'(\|.*?)?\]\]", _repl, text)
    # Strip accidental backticks wrapping wikilinks: `[[note]]` -> [[note]] or `[[note|alias]]` -> [[note|alias]]
    text = re.sub(r"`(!?\[\[[^`\n]+?\]\])`", r"\1", text)
    text = heal_artifact_embed_syntax(text)
    text = heal_html_entity_leakage(text)
    return text


def heal_artifact_embed_syntax(text: str) -> str:
    """Normalize malformed snake_cased diagram extensions inside embed wikilinks.

    Examples:
        ![[foo_excalidraw_md]] -> ![[foo.excalidraw.md]]
        ![[foo_excalidraw_md|100%]] -> ![[foo.excalidraw.md|100%]]
        ![[bar_mermaid_md|800]] -> ![[bar.mermaid.md|800]]
        ![[baz_d2_svg]] -> ![[baz.d2.svg]]

    Args:
        text: Input markdown text.

    Returns:
        Sanitized markdown text with valid diagram extensions.
    """
    text = re.sub(r"!\[\[([^\]|]+)_excalidraw_md(\|[^\]]*)?\]\]", r"![[\1.excalidraw.md\2]]", text)
    text = re.sub(r"!\[\[([^\]|]+)_mermaid_md(\|[^\]]*)?\]\]", r"![[\1.mermaid.md\2]]", text)
    text = re.sub(r"!\[\[([^\]|]+)_d2_svg(\|[^\]]*)?\]\]", r"![[\1.d2.svg\2]]", text)
    return text



def reindex_citations(response: str, rag_refs: dict[int, tuple[str, str]]) -> str:
    """Reindex numeric citations in response ([14] -> [1]) and append reference list.

    Args:
        response: LLM response containing citations like [14] or |[14]|.
        rag_refs: Mapping of reference IDs to (filename, file_title).

    Returns:
        Response with reindexed citations and appended '## Tài liệu tham chiếu' section.
    """
    if not rag_refs:
        return response

    used_ids: list[int] = []
    for match in re.finditer(r"\[(\d+)\]|\|\[?(\d+)\]?\]\]", response):
        val = match.group(1) or match.group(2)
        if val:
            try:
                parsed_id = int(val)
                if parsed_id not in used_ids:
                    used_ids.append(parsed_id)
            except ValueError:
                pass

    if not used_ids:
        return response

    valid_ids = [i for i in used_ids if i in rag_refs]
    if not valid_ids:
        return response

    id_map = {old_id: new_id for new_id, old_id in enumerate(valid_ids, 1)}

    def _replace_id(match: re.Match) -> str:
        if match.group(1):
            old_id = int(match.group(1))
            if old_id in id_map:
                return f"[{id_map[old_id]}]"
        elif match.group(2):
            old_id = int(match.group(2))
            if old_id in id_map:
                original = match.group(0)
                if f"[{old_id}]" in original:
                    return original.replace(f"[{old_id}]", f"[{id_map[old_id]}]")
                else:
                    return original.replace(str(old_id), str(id_map[old_id]))
        return match.group(0)

    response = re.sub(r"\[(\d+)\]|\|\[?(\d+)\]?\]\]", _replace_id, response)

    ref_block = "\n\n---\n\n## Tài liệu tham chiếu\n"
    for old_id in valid_ids:
        fname, ftitle = rag_refs[old_id]
        new_id = id_map[old_id]
        ref_block += f"{new_id}. [[{fname}|{ftitle}]]\n"

    if "]. [[" in ref_block or ". [[" in ref_block:
        response += ref_block

    return response
