import os
import re
from pathlib import Path

target_dir = Path(r'G:\My Drive\VvC_Vault\04 - Permanent\concepts')
all_files = list(target_dir.glob('*.md'))

duplicate_pattern = re.compile(r'^(.*)_(\d+)(?:_(\d+))?\.md$')
deleted_count = 0

print("Scanning for duplicates...")
for f in all_files:
    match = duplicate_pattern.match(f.name)
    if match:
        base_stem = match.group(1)
        original_file = target_dir / f"{base_stem}.md"
        
        # If the original file exists, this is a true duplicate generated by post_process.py
        if original_file.exists():
            print(f"Deleting duplicate: {f.name} (Original exists: {base_stem}.md)")
            f.unlink()
            deleted_count += 1
            
print(f'\nTotal duplicates deleted: {deleted_count}')
